### ISSUE TITLE
Erro na alteração do nome do usuário

### ISSUE THREAD

**Issue by VictorRodriguesS0** [fga-eps-mds/2018.2-FGAPP-FrontEnd#117]
**Descreva o bug**
Na tela de Perfil do usuário, ao tentar colocar ou mudar o nome de usuário, o aplicativo apresenta a mensagem de erro "Email inválido", mesmo já tenho o e-mail do usuário supostamente "preenchido"

**Para reproduzir**
Passos para reproduzir o comportamento:
1. Abra o integra.
2. Faça o Login
3. Navegue até a ultima aba a direita
4. Tente atualizar o nome e veja o erro!

**Comportamento esperado**
O usuário preenche apenas o campo de nome, clica em salvar e tem o retorno de sucesso!

**Screenshots**
![photo_2018-11-21_23-58-10](https://user-images.githubusercontent.com/20848512/48878167-70c83080-eded-11e8-92b5-e6c42e7f7918.jpg)
![photo_2018-11-21_23-58-02](https://user-images.githubusercontent.com/20848512/48878169-73c32100-eded-11e8-9a6a-03201d9b7917.jpg)
![photo_2018-11-21_23-58-00](https://user-images.githubusercontent.com/20848512/48878172-76257b00-eded-11e8-9ea9-77c9767eda78.jpg)

**Smartphone:**
 - Device: OnePlus 6
 - OS: Android 
 - Version: 9.0.2 Pie
- 
 - Device: Samsung Galaxy J7 PRO
 - OS: Android 
 - Version: 8.1.0 Oreo

**Comment by juniopereirab** [comment]
Olá, de fato esse bug existia, porém já foi solucionado recentemente, estou esperando apenas a avaliação do pull request fga-eps-mds/2018.2-FGAPP-login#34.

**Comment by gleal17** [comment]
Valeu pelo feedback @juniopereirab. Poderia fechar a issue quando o PR for aprovado?

**Comment by juniopereirab** [comment]
Claro, sem problemas!
