### ISSUE TITLE
Bug - Login

### ISSUE THREAD

**Issue by zarbielli** [fga-eps-mds/2018.2-FGAPP-FrontEnd#143]
**Describe the bug**
The app doesn't keep you logged in after you close it.

**To Reproduce**
1. Open the App
2. Make a login
3. Close the App
4. Open it again

**Expected behavior**
The app most keep you logged in until you log out, even if the app is open or close

**Smartphone:**
 - Device: Xiaomi Mi A2 Lite
 - OS: Android 8.1.0

**Comment by shayanealcantara** [comment]
@zarbielli Este bug foi resolvido com este PR #90, logo estou fechando a issue. Obrigada.
