### ISSUE TITLE
Erro ao dar make

### ISSUE THREAD

**Issue by andrelucax** [fga-eps-mds/2018.2-FGAPP-FrontEnd#2]
**Describe the bug**
Estou tendo esse erro ao dar o comando `make`

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubunto 16.04

**Smartphone (please complete the following information):**

**Additional context**
```
make[1]: Leaving directory '/home/andrelucax/docker-mds/2018.2-FGAPP-FrontEnd/mobile'
make run
make[1]: Entering directory '/home/andrelucax/docker-mds/2018.2-FGAPP-FrontEnd/mobile'
python get-ip-address.py
127.0.1.1
docker run -it --rm -p 19000:19000 -p 19001:19001 -v ":/app" --env-file .env react-app:integra bash -c "yarn install; bash"
docker: Error response from daemon: invalid volume spec ":/app": invalid volume specification: ':/app'.
See 'docker run --help'.
Makefile:6: recipe for target 'run' failed
make[1]: *** [run] Error 125
make[1]: Leaving directory '/home/andrelucax/docker-mds/2018.2-FGAPP-FrontEnd/mobile'
Makefile:2: recipe for target 'default' failed
make: *** [default] Error 2
```

**Comment by lucasca73** [comment]
O erro esta relacionado com o mapeamento do volume. @andrelucax  Pode mandar aqui como esta escrito o makefile, ele deveria estar parecido com isso ```... -v ${PWD}:"/app"  ...```

**Comment by andrelucax** [comment]
`docker run -it --rm -p 19000:19000 -p 19001:19001 -v "${PWD}:/app" --env-file .env react-app:integra bash -c "yarn install; bash"`

**Comment by lucasca73** [comment]
Parece que seu SO não está pegando a variável de caminho do projeto pra passar pro docker run. Um compose pode mapear melhor isso. Vou passar essa issue pra Doing.

**Comment by lucasca73** [comment]
@andrelucax foi inserido o docker-compose, pra gerenciar melhor as configurações do container. 
Depois de instalar ele vai segurar a tela, abra uma nova aba do terminal, e execute o run.

## Install
```shell
make
or
make build
```
## Run
```shell
make run
```

## Down
```shell
make down
```
