### ISSUE TITLE
Erro ao executar yarn start

### ISSUE THREAD

**Issue by gustavolima00** [fga-eps-mds/2018.2-FGAPP-FrontEnd#4]
**Sistema**
Ubuntu 18.04

**O que foi feito**
Ao dar clone no repositório foi executado:
`sudo make`
`yarn start`

**Me foi retornado esse erro no terminal**

![image](https://user-images.githubusercontent.com/32046134/45580398-0d5ad900-b867-11e8-92f5-9082b70d79bf.png)

**A seguir tem o erro da imagem digitado:**
```
`yarn run v1.3.2
$ react-native-scripts-ts start
00:37:03: Starting packager...
***ERROR STARTING PACKAGER***

Error: Missing app.json. See https://docs.expo.io/
00:37:10: Error starting packager: Error: Couldn't start project. Please fix the errors and restart the project.
    at /xdl/src/Project.js:1329:11
    at Generator.next (<anonymous>)
    at step (/app/node_modules/xdl/build/Project.js:1735:191)
    at /app/node_modules/xdl/build/Project.js:1735:361
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
`
```

**Comment by lucasca73** [comment]
@gustavolima00 Tenta dar o **make** de novo, e espera ele dar o done, demora um pouco, mas ele gera esse arquivo que esta faltando.

**Comment by gustavolima00** [comment]
Continua dando o mesmo erro após executar o make novamente.

**Comment by lucasca73** [comment]
Veja como esta o seu diretório dentro do container, @gustavolima00 teria como dar um ```ls``` e mostrar o conteúdo aqui?

O erro acusa que o ```app.json``` esta faltando, mas ele esta no git do projeto. [app.json](https://github.com/fga-eps-mds/2018.2-FGAPP-FrontEnd/blob/master/mobile/app.json)

**Comment by gustavolima00** [comment]
Resolvi o problema, parece que algum arquivo foi removido, resolvi ao rodar:
`git reset --hard`
