### ISSUE TITLE
Vendas-app/Login-screen

### ISSUE THREAD

**Issue by andrelucax** [fga-eps-mds/2018.2-FGAPP-FrontEnd#40]
**Describe the bug**
if screen has error message (like unable to log with credencials) when keyboard pops up buttons overlap message

**To Reproduce**
1. Go to Login Screen
2. Click on 'ENTRAR' with invalid credentials (blank inputs will work but not as the image, to see better  put password without email)
3. See error

**Expected behavior**
It is expected that buttons do not overlap any message

**Screenshots**
![error](https://user-images.githubusercontent.com/42394759/46708983-e7cbb000-cc17-11e8-9ddc-ecdeb7e25452.jpg)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device:Samsumg J7

**Additional context**
deppending on error, the error text appears in different places

**Comment by lucasca73** [comment]
@andrelucax qual o status dessa issue mano?

**Comment by lucasca73** [comment]
@andrelucax qual o status dessa issue? (Quem deletou o comentário passado, por favor não faça isso sem antes avisar...)

**Comment by lucasca73** [comment]
.

**Comment by andrelucax** [comment]
@lucasca73 Ate' onde eu saiba/vi ninguem se disponibilizou a fazer a issue ainda, entao segue sem andamento... Eu dei prioridade as historias de usuario pois estava com a agenda meio apertada. Abracos

**Comment by shayanealcantara** [comment]
Este bug foi solucionado no PR #138 , logo estou fechando a issue.
