### ISSUE TITLE
Problemas para a executação da aplicação de React Native pelo Expo.

### ISSUE THREAD

**Issue by juniopereirab** [fga-eps-mds/2018.2-FGAPP-FrontEnd#5]
**Describe the bug**
Não estou conseguindo acessar o server JS (nem pelo NPM, nem pelo YARN), no EXPO pelo celular.

**To Reproduce**
1. Eu dei ``` sudo make ```
2. Aguardei a inicialização do docker-compose e então abri uma nova aba do terminal e dei ```sudo make run``` para que o docker fosse iniciado
3. Então, eu dei ```yarn start```, e rodei a aplicação que exibiu o QR code corretamente.
4. Então a aplicação não rodou no meu celular corretamente.

**Expected behavior**
Eu esperava que a aplicação em React Native rodasse corretamente.

Abaixo seguem anexos, as formas de conexão que eu tentei, atráves do link local usando o Mozilla Firefox (pois o Chrome não abria o app), atráves do email, e também pela leitura do QR Code.

**Screenshots**
![Imgur](https://i.imgur.com/mNVmnGP.jpg)
![Imgur](https://i.imgur.com/7ICbL8Z.jpg)
![Imgur](https://i.imgur.com/Pp6lZQq.jpg)
![Imgur](https://i.imgur.com/JGcux2w.jpg)
![Imgur](https://i.imgur.com/0LbZCyS.jpg)
![Imgur](https://i.imgur.com/KEvOpJz.jpg)

**Desktop (please complete the following information):**
 - OS: Ubuntu 16.04
 - Browser: Google Chrome

**Smartphone (please complete the following information):**
 - Device: Motorola Moto G6
 - OS: Android 8.0.0
 - Browser: Google Chrome (não funciona para abrir link) / Mozilla

**Comment by lucasca73** [comment]
Estou dando uma olhada aqui e o script de pegar ip do python ele retorna 127.0.0.1 quando está offline.
Ou o mapeamento de rede esta apontando pro localhost. De acordo com esse [stackoverflow](https://stackoverflow.com/questions/13947178/why-socket-gethostbynamesocket-getfqdn-and-socket-gethostbynamesocket-getho). 

Acredito que não seja problema com o arquivo /etc/hosts.

**Comment by lucasca73** [comment]
@juniopereirab @gustavolima00. Atualizem a branch e testem ai, o contorno para manual possibilita vocês trabalharem tranquilos.

**Comment by lucasca73** [comment]
ainda esta nebuloso o porquê desse script não capturar essa informação adequadamente... Mas adicionei mensagens de erro e quando ocorrer algo inesperado, a mensagem para resolver o problema.
