### ISSUE TITLE
Erro ao logar..

### ISSUE THREAD

**Issue by juniopereirab** [fga-eps-mds/2018.2-FGAPP-FrontEnd#70]
**Describe the bug**
Quando eu tento logar ao app, aparece o erro abaixo:

<p align="center">
    <img src="https://user-images.githubusercontent.com/17153869/47883556-2d8d2a00-de0c-11e8-96f6-b263db1f9523.png" alt="erro" width="213" height="435">
</p>

**To Reproduce**
1. Rodei todos os repositórios de microserviço na "dev"
2. Rodei o front-end dando yarn start
3. Tentei logar com uma conta existente no app
4. Apareceu o erro

**Expected behavior**
Eu esperava poder logar e navegar pelo aplicativo

**Desktop:**
 - OS: Ubuntu 16.04

**Smartphone:**
 - Device: Moto G6
 - OS: Android 8.0

**Comment by juniopereirab** [comment]
O comportamento no terminal sobre as requisições que foram feitas ao microsserviço de produtos foram esses: 

![image](https://user-images.githubusercontent.com/17153869/47883806-4813d300-de0d-11e8-987f-e965e2e6c78d.png)

**Comment by andrelucax** [comment]
Nao consegui reproduzir o erro.. @juniopereirab 

1 - Tente dar git pull em todos os repositorios para garantir que estao sendo rodados em sua ultima versao da dev
2 - `$ make` nao esta fazendo migrations direto em alguns microservices foi substituido por `$ make build` dps `$ make`
3 - Verifique o .env dos microservices que necessitam de tal
4 - Tente apagar o banco de dados dos microservices e rodar novamente (verifique as migrations, que tambem podem ser excluidas)

**Comment by juniopereirab** [comment]
Após ter dado git pull em todos os repositórios, make build e make em todos os repositórios que foi possível fazer isso. Verifiquei todos os .envs que são necessários (repositórios do Front-End, Login e Api-Gateway), rodei também `npm install` dentro do docker do front, para instalar possíveis atualizações. Me deparo com o seguinte erro, que impede que o app de bundle:

![image](https://user-images.githubusercontent.com/17153869/47884957-90cd8b00-de11-11e8-8887-65ab38cc1652.png)
<p align="center">
    <img src="https://user-images.githubusercontent.com/17153869/47885042-ebff7d80-de11-11e8-864b-c7560494c2de.png" width="213" height="435">
    <img src="https://user-images.githubusercontent.com/17153869/47885046-f3268b80-de11-11e8-9720-a1ed40739074.png" width="213" height="435">
</p>

**Comment by juniopereirab** [comment]
O erro foi encontrado, ao me basear no env-reference acabei enviando requisições para o lugar errado, e acredito que para alguém que vá rodar nosso app, é importante que ele esteja certo. Por isso, estou fechando essa issue. E vou mudar o env-reference para as respectivas portas dos microsserviços.

Atual env-reference da API_GATEWAY:
![image](https://user-images.githubusercontent.com/17153869/47886279-dee58d00-de17-11e8-8843-3763224799e3.png)

**Comment by andrelucax** [comment]
Boa observacao, grato por ter percebido e arrumado, e' para isso mesmo que serve o env-reference

**Comment by lucasca73** [comment]
@juniopereirab esses caminhos estão corretos quando os serviços estão em ambiente de desenvolvimento. Para acessar em rede do computador utilizando o IP, que as portas mudariam.

no react-native 
utiliza-se
```
>> para o login
http://192.168.25.3:8000

>> para o order
http://192.168.25.3:8001

>> para o product
http://192.168.25.3:8002

>> para o notification
http://192.168.25.3:8003

>> para a api-gateway
http://192.168.25.3:5000
```

Os serviços de product, order e notification sendo encapsulados pela api-gateway.

**Comment by andrelucax** [comment]
O que o @lucasca73 disse esta correto. Porém acho que na env-reference deveriam ter ambas as possibilidades, pra poder se basear na necessária
