### ISSUE TITLE
Erro desconhecido no Settings e Validação para câmera

### ISSUE THREAD

**Issue by lucasca73** [fga-eps-mds/2018.2-FGAPP-FrontEnd#97]
**Describe the bug**
Ao entrar no perfil localizado no settings ocorre um erro.

**Device**
iPhone XS

<img src="https://user-images.githubusercontent.com/4529055/48461739-4d353280-e7bc-11e8-8121-7c527980bb57.gif" width=350>

**Comment by VictorRodriguesS0** [comment]
Bug não acontece mais, na atual versão do app! Fechando a issue.
